"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/accounts";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/accounts";
export const listBankAccounts: typeof server.listBankAccounts = backgroundRead("accounts.listBankAccounts", server.listBankAccounts);
export const listCashAccounts: typeof server.listCashAccounts = backgroundRead("accounts.listCashAccounts", server.listCashAccounts);
export const listCheques: typeof server.listCheques = backgroundRead("accounts.listCheques", server.listCheques);
export const updateBankAccount: typeof server.updateBankAccount = backgroundAction("accounts.updateBankAccount", server.updateBankAccount);
export const deleteBankAccount: typeof server.deleteBankAccount = backgroundAction("accounts.deleteBankAccount", server.deleteBankAccount);
export const createBankAccountsBatch: typeof server.createBankAccountsBatch = backgroundAction("accounts.createBankAccountsBatch", server.createBankAccountsBatch);
export const updateCashAccount: typeof server.updateCashAccount = backgroundAction("accounts.updateCashAccount", server.updateCashAccount);
export const deleteCashAccount: typeof server.deleteCashAccount = backgroundAction("accounts.deleteCashAccount", server.deleteCashAccount);
export const createCashAccountsBatch: typeof server.createCashAccountsBatch = backgroundAction("accounts.createCashAccountsBatch", server.createCashAccountsBatch);
export const createCheque: typeof server.createCheque = backgroundAction("accounts.createCheque", server.createCheque);
export const createChequesBatch: typeof server.createChequesBatch = backgroundAction("accounts.createChequesBatch", server.createChequesBatch);
export const updateCheque: typeof server.updateCheque = backgroundAction("accounts.updateCheque", server.updateCheque);
export const deleteCheque: typeof server.deleteCheque = backgroundAction("accounts.deleteCheque", server.deleteCheque);
