"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/brands";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/brands";
export const listBrands: typeof server.listBrands = backgroundRead("brands.listBrands", server.listBrands);
export const createBrandsBatch: typeof server.createBrandsBatch = backgroundAction("brands.createBrandsBatch", server.createBrandsBatch);
export const updateBrand: typeof server.updateBrand = backgroundAction("brands.updateBrand", server.updateBrand);
export const deleteBrand: typeof server.deleteBrand = backgroundAction("brands.deleteBrand", server.deleteBrand);
