"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/categories";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/categories";
export const listCategoryTree: typeof server.listCategoryTree = backgroundRead("categories.listCategoryTree", server.listCategoryTree);
export const saveCategoryTree: typeof server.saveCategoryTree = backgroundAction("categories.saveCategoryTree", server.saveCategoryTree);
export const getCategory: typeof server.getCategory = backgroundRead("categories.getCategory", server.getCategory);
export const createCategoriesBatch: typeof server.createCategoriesBatch = backgroundAction("categories.createCategoriesBatch", server.createCategoriesBatch);
export const updateCategory: typeof server.updateCategory = backgroundAction("categories.updateCategory", server.updateCategory);
export const deleteCategory: typeof server.deleteCategory = backgroundAction("categories.deleteCategory", server.deleteCategory);
