"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/companies";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/companies";
export const listCompanies: typeof server.listCompanies = backgroundRead("companies.listCompanies", server.listCompanies);
export const getCompany: typeof server.getCompany = backgroundRead("companies.getCompany", server.getCompany);
export const createCompaniesBatch: typeof server.createCompaniesBatch = backgroundAction("companies.createCompaniesBatch", server.createCompaniesBatch);
export const updateCompany: typeof server.updateCompany = backgroundAction("companies.updateCompany", server.updateCompany);
export const deleteCompany: typeof server.deleteCompany = backgroundAction("companies.deleteCompany", server.deleteCompany);
