"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/contacts";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/contacts";
export const listContacts: typeof server.listContacts = backgroundRead("contacts.listContacts", server.listContacts);
export const getContact: typeof server.getContact = backgroundRead("contacts.getContact", server.getContact);
export const createContactsBatch: typeof server.createContactsBatch = backgroundAction("contacts.createContactsBatch", server.createContactsBatch);
export const getContactsForEdit: typeof server.getContactsForEdit = backgroundRead("contacts.getContactsForEdit", server.getContactsForEdit);
export const updateContactsBatch: typeof server.updateContactsBatch = backgroundAction("contacts.updateContactsBatch", server.updateContactsBatch);
export const updateContact: typeof server.updateContact = backgroundAction("contacts.updateContact", server.updateContact);
export const listContactMergeCandidates: typeof server.listContactMergeCandidates = backgroundRead("contacts.listContactMergeCandidates", server.listContactMergeCandidates);
export const mergeContacts: typeof server.mergeContacts = backgroundAction("contacts.mergeContacts", server.mergeContacts);
