"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/expenses";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/expenses";
export const listExpenses: typeof server.listExpenses = backgroundRead("expenses.listExpenses", server.listExpenses);
export const listChequesForExpenses: typeof server.listChequesForExpenses = backgroundRead("expenses.listChequesForExpenses", server.listChequesForExpenses);
export const createExpensesBatch: typeof server.createExpensesBatch = backgroundAction("expenses.createExpensesBatch", server.createExpensesBatch);
export const createExpense: typeof server.createExpense = backgroundAction("expenses.createExpense", server.createExpense);
export const updateExpense: typeof server.updateExpense = backgroundAction("expenses.updateExpense", server.updateExpense);
export const deleteExpense: typeof server.deleteExpense = backgroundAction("expenses.deleteExpense", server.deleteExpense);
