"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/ledger";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/ledger";
export const listLedgerBalances: typeof server.listLedgerBalances = backgroundRead("ledger.listLedgerBalances", server.listLedgerBalances);
export const listPaymentLedgerBalances: typeof server.listPaymentLedgerBalances = backgroundRead("ledger.listPaymentLedgerBalances", server.listPaymentLedgerBalances);
export const createOpeningBalanceEntry: typeof server.createOpeningBalanceEntry = backgroundAction("ledger.createOpeningBalanceEntry", server.createOpeningBalanceEntry);
export const setContactBalance: typeof server.setContactBalance = backgroundAction("ledger.setContactBalance", server.setContactBalance);
export const getPartyLedger: typeof server.getPartyLedger = backgroundRead("ledger.getPartyLedger", server.getPartyLedger);
export const deleteLedgerRow: typeof server.deleteLedgerRow = backgroundAction("ledger.deleteLedgerRow", server.deleteLedgerRow);
export const getPartyOpeningBalance: typeof server.getPartyOpeningBalance = backgroundRead("ledger.getPartyOpeningBalance", server.getPartyOpeningBalance);
export const setPartyOpeningBalance: typeof server.setPartyOpeningBalance = backgroundAction("ledger.setPartyOpeningBalance", server.setPartyOpeningBalance);
export const previewLedgerRowDelete = server.previewLedgerRowDelete;
export const previewLedgerRowAmount = server.previewLedgerRowAmount;
export const previewLedgerRowDate = server.previewLedgerRowDate;
export const previewPartyOpeningBalance = server.previewPartyOpeningBalance;
export const getPartyAuditTrail: typeof server.getPartyAuditTrail = backgroundRead("ledger.getPartyAuditTrail", server.getPartyAuditTrail);
export const getLedgerInlineOptions: typeof server.getLedgerInlineOptions = backgroundRead("ledger.getLedgerInlineOptions", server.getLedgerInlineOptions);
