"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/locations";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/locations";
export const listLocations: typeof server.listLocations = backgroundRead("locations.listLocations", server.listLocations);
export const createLocationsBatch: typeof server.createLocationsBatch = backgroundAction("locations.createLocationsBatch", server.createLocationsBatch);
export const updateLocation: typeof server.updateLocation = backgroundAction("locations.updateLocation", server.updateLocation);
export const deleteLocation: typeof server.deleteLocation = backgroundAction("locations.deleteLocation", server.deleteLocation);
