"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/payments";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/payments";
export const listPayments: typeof server.listPayments = backgroundRead("payments.listPayments", server.listPayments);
export const listPaymentsPage: typeof server.listPaymentsPage = backgroundRead("payments.listPaymentsPage", server.listPaymentsPage);
export const listChequesForPayments: typeof server.listChequesForPayments = backgroundRead("payments.listChequesForPayments", server.listChequesForPayments);
export const createPayment: typeof server.createPayment = backgroundAction("payments.createPayment", server.createPayment);
export const getPayment: typeof server.getPayment = backgroundRead("payments.getPayment", server.getPayment);
export const createPaymentsBatch: typeof server.createPaymentsBatch = backgroundAction("payments.createPaymentsBatch", server.createPaymentsBatch);
export const updatePayment: typeof server.updatePayment = backgroundAction("payments.updatePayment", server.updatePayment);
export const deletePayment: typeof server.deletePayment = backgroundAction("payments.deletePayment", server.deletePayment);
