"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/products";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/products";
export const listProductsWithRates: typeof server.listProductsWithRates = backgroundRead("products.listProductsWithRates", server.listProductsWithRates);
export const peekNextSku = server.peekNextSku;
export const getProductAssignmentOptions: typeof server.getProductAssignmentOptions = backgroundRead("products.getProductAssignmentOptions", server.getProductAssignmentOptions);
export const assignBaseUnitToProducts: typeof server.assignBaseUnitToProducts = backgroundAction("products.assignBaseUnitToProducts", server.assignBaseUnitToProducts);
export const createProductsBatch: typeof server.createProductsBatch = backgroundAction("products.createProductsBatch", server.createProductsBatch);
export const getProductsForEdit: typeof server.getProductsForEdit = backgroundRead("products.getProductsForEdit", server.getProductsForEdit);
export const updateProductsBatch: typeof server.updateProductsBatch = backgroundAction("products.updateProductsBatch", server.updateProductsBatch);
export const listMergeCandidates: typeof server.listMergeCandidates = backgroundRead("products.listMergeCandidates", server.listMergeCandidates);
export const mergeProducts: typeof server.mergeProducts = backgroundAction("products.mergeProducts", server.mergeProducts);
export const exportProductsCsv = server.exportProductsCsv;
export const importProductsCsv = server.importProductsCsv;
