"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/purchases";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/purchases";
export const listStockPurchases: typeof server.listStockPurchases = backgroundRead("purchases.listStockPurchases", server.listStockPurchases);
export const listStockPurchasesPage: typeof server.listStockPurchasesPage = backgroundRead("purchases.listStockPurchasesPage", server.listStockPurchasesPage);
export const getStockPurchase: typeof server.getStockPurchase = backgroundRead("purchases.getStockPurchase", server.getStockPurchase);
export const listChequesForPurchases: typeof server.listChequesForPurchases = backgroundRead("purchases.listChequesForPurchases", server.listChequesForPurchases);
export const createStockPurchase: typeof server.createStockPurchase = backgroundAction("purchases.createStockPurchase", server.createStockPurchase);
export const updateStockPurchase: typeof server.updateStockPurchase = backgroundAction("purchases.updateStockPurchase", server.updateStockPurchase);
export const deleteStockPurchase: typeof server.deleteStockPurchase = backgroundAction("purchases.deleteStockPurchase", server.deleteStockPurchase);
export const listPurchaseMergeCandidates: typeof server.listPurchaseMergeCandidates = backgroundRead("purchases.listPurchaseMergeCandidates", server.listPurchaseMergeCandidates);
export const mergeStockPurchases: typeof server.mergeStockPurchases = backgroundAction("purchases.mergeStockPurchases", server.mergeStockPurchases);
export const exportStockPurchasesCsv = server.exportStockPurchasesCsv;
export const importStockPurchasesCsv = server.importStockPurchasesCsv;
