"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/quotations";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/quotations";
export const listQuotations: typeof server.listQuotations = backgroundRead("quotations.listQuotations", server.listQuotations);
export const listQuotationsPage: typeof server.listQuotationsPage = backgroundRead("quotations.listQuotationsPage", server.listQuotationsPage);
export const getQuotation: typeof server.getQuotation = backgroundRead("quotations.getQuotation", server.getQuotation);
export const createQuotation: typeof server.createQuotation = backgroundAction("quotations.createQuotation", server.createQuotation);
export const updateQuotation: typeof server.updateQuotation = backgroundAction("quotations.updateQuotation", server.updateQuotation);
export const deleteQuotation: typeof server.deleteQuotation = backgroundAction("quotations.deleteQuotation", server.deleteQuotation);
export const convertQuotation: typeof server.convertQuotation = backgroundAction("quotations.convertQuotation", server.convertQuotation);
export const conversionsOf = server.conversionsOf;
export const quotationsForDocuments = server.quotationsForDocuments;
