"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/returns";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/returns";
export const getReturnableSale: typeof server.getReturnableSale = backgroundRead("returns.getReturnableSale", server.getReturnableSale);
export const createSalesReturn: typeof server.createSalesReturn = backgroundAction("returns.createSalesReturn", server.createSalesReturn);
export const cancelSalesReturn: typeof server.cancelSalesReturn = backgroundAction("returns.cancelSalesReturn", server.cancelSalesReturn);
