"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/sales";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/sales";
export const listSales: typeof server.listSales = backgroundRead("sales.listSales", server.listSales);
export const listChequesForSales: typeof server.listChequesForSales = backgroundRead("sales.listChequesForSales", server.listChequesForSales);
export const getCustomerOutstanding: typeof server.getCustomerOutstanding = backgroundRead("sales.getCustomerOutstanding", server.getCustomerOutstanding);
export const getSaleEditorOptions: typeof server.getSaleEditorOptions = backgroundRead("sales.getSaleEditorOptions", server.getSaleEditorOptions);
export const getSale: typeof server.getSale = backgroundRead("sales.getSale", server.getSale);
export const getInvoice: typeof server.getInvoice = backgroundRead("sales.getInvoice", server.getInvoice);
export const createSale: typeof server.createSale = backgroundAction("sales.createSale", server.createSale);
export const updateSale: typeof server.updateSale = backgroundAction("sales.updateSale", server.updateSale);
export const deleteSale: typeof server.deleteSale = backgroundAction("sales.deleteSale", server.deleteSale);
