"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/settings";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/settings";
export const getSettings: typeof server.getSettings = backgroundRead("settings.getSettings", server.getSettings);
export const saveSettings: typeof server.saveSettings = backgroundAction("settings.saveSettings", server.saveSettings);
export const settingsOverview = server.settingsOverview;
