"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/taxes";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/taxes";
export const listTaxes: typeof server.listTaxes = backgroundRead("taxes.listTaxes", server.listTaxes);
export const getTax: typeof server.getTax = backgroundRead("taxes.getTax", server.getTax);
export const createTaxesBatch: typeof server.createTaxesBatch = backgroundAction("taxes.createTaxesBatch", server.createTaxesBatch);
export const updateTax: typeof server.updateTax = backgroundAction("taxes.updateTax", server.updateTax);
export const deleteTax: typeof server.deleteTax = backgroundAction("taxes.deleteTax", server.deleteTax);
