"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/units";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/units";
export const listUnits: typeof server.listUnits = backgroundRead("units.listUnits", server.listUnits);
export const getUnit: typeof server.getUnit = backgroundRead("units.getUnit", server.getUnit);
export const createUnitsBatch: typeof server.createUnitsBatch = backgroundAction("units.createUnitsBatch", server.createUnitsBatch);
export const updateUnit: typeof server.updateUnit = backgroundAction("units.updateUnit", server.updateUnit);
export const deleteUnit: typeof server.deleteUnit = backgroundAction("units.deleteUnit", server.deleteUnit);
export const mergeUnits: typeof server.mergeUnits = backgroundAction("units.mergeUnits", server.mergeUnits);
