"use client";
// Generated by scripts/generate-background-actions.mjs.
import * as server from "@/lib/actions/unit-conversions";
import { backgroundAction, backgroundRead } from "@/lib/background-client";
export type * from "@/lib/actions/unit-conversions";
export const listUnitConversions: typeof server.listUnitConversions = backgroundRead("unit-conversions.listUnitConversions", server.listUnitConversions);
export const getUnitConversion: typeof server.getUnitConversion = backgroundRead("unit-conversions.getUnitConversion", server.getUnitConversion);
export const createUnitConversion: typeof server.createUnitConversion = backgroundAction("unit-conversions.createUnitConversion", server.createUnitConversion);
export const updateUnitConversion: typeof server.updateUnitConversion = backgroundAction("unit-conversions.updateUnitConversion", server.updateUnitConversion);
export const setUnitConversionRuleItems: typeof server.setUnitConversionRuleItems = backgroundAction("unit-conversions.setUnitConversionRuleItems", server.setUnitConversionRuleItems);
export const assignUnitConversionRuleToItems: typeof server.assignUnitConversionRuleToItems = backgroundAction("unit-conversions.assignUnitConversionRuleToItems", server.assignUnitConversionRuleToItems);
export const deleteUnitConversion: typeof server.deleteUnitConversion = backgroundAction("unit-conversions.deleteUnitConversion", server.deleteUnitConversion);
