"use client";

import { formatDate, money, qty } from "@/lib/format";
import { downloadInvoicePdf, type Invoice } from "@/lib/invoice-pdf";

export type { Invoice };

// The invoice as a web page — read it, check it, hand the screen to someone.
// The file people actually send out is generated by lib/invoice-pdf.ts, which
// draws this same layout into a real PDF.
//
// The two are separate layouts and have to be edited together. That's the price
// of a one-click download: the browser cannot write a PDF to disk without its
// print dialog, so producing a file with no dialog means drawing it ourselves.
// The print styles here still work if anyone hits Ctrl+P.


// Same generator the invoice list's row button uses, so there is one way to
// produce a PDF rather than a print dialog here and a real file there.
export function DownloadInvoiceButton({ invoice }: { invoice: Invoice }) {
  return (
    <button
      type="button"
      onClick={() => downloadInvoicePdf(invoice)}
      className="h-11 rounded bg-navy-800 px-5 text-sm font-semibold text-white hover:bg-navy-700 print:hidden"
    >
      Download PDF
    </button>
  );
}

export function InvoiceDocument({ invoice }: { invoice: Invoice }) {
  const balance = Number(invoice.grandTotal) - Number(invoice.paidAmount);
  const discount = Number(invoice.discountTotal);
  const tax = Number(invoice.taxTotal);
  const shipping = Number(invoice.shippingTotal);

  return (
    <div className="mx-auto w-full max-w-3xl rounded-lg border border-sand bg-white p-8 text-ink print:max-w-none print:rounded-none print:border-0 print:p-0">
      <div className="flex flex-wrap items-start justify-between gap-6 border-b border-sand pb-6">
        <div>
          <h1 className="text-2xl font-semibold text-navy-800">{invoice.companyName}</h1>
          {invoice.companyAddress && <p className="mt-1 whitespace-pre-line text-sm text-steel">{invoice.companyAddress}</p>}
          <p className="mt-1 text-sm text-steel">
            {[invoice.companyPhone, invoice.companyEmail].filter(Boolean).join(" · ")}
          </p>
          {invoice.companyTaxNumber && <p className="text-sm text-steel">NTN: {invoice.companyTaxNumber}</p>}
        </div>
        <div className="text-right">
          <p className="text-xs font-semibold uppercase tracking-wide text-steel">Invoice</p>
          <p className="text-xl font-semibold text-navy-800">{invoice.number}</p>
          <p className="mt-1 text-sm text-steel">{formatDate(invoice.documentDate)}</p>
          <p className="mt-2 text-sm font-semibold text-ink">
            {invoice.isPaid ? "Paid" : Number(invoice.paidAmount) > 0 ? "Part paid" : "Unpaid"}
          </p>
        </div>
      </div>

      <div className="py-6">
        <p className="text-xs font-semibold uppercase tracking-wide text-steel">Billed to</p>
        <p className="mt-1 text-base font-medium text-ink">{invoice.customerName ?? "—"}</p>
        {invoice.customerAddress && <p className="whitespace-pre-line text-sm text-steel">{invoice.customerAddress}</p>}
        <p className="text-sm text-steel">{[invoice.customerCity, invoice.customerPhone].filter(Boolean).join(" · ")}</p>
      </div>

      <div className="scroll-thin overflow-x-auto print:overflow-visible">
        <table className="w-full min-w-[30rem] border-collapse text-sm print:min-w-0">
        <thead>
          <tr className="border-y border-sand">
            <th className="w-10 py-2 text-right text-xs font-semibold uppercase tracking-wide text-steel">#</th>
            <th className="py-2 text-left text-xs font-semibold uppercase tracking-wide text-steel">Item</th>
            <th className="w-24 py-2 text-right text-xs font-semibold uppercase tracking-wide text-steel">Qty</th>
            <th className="w-28 py-2 text-right text-xs font-semibold uppercase tracking-wide text-steel">Rate</th>
            <th className="w-32 py-2 text-right text-xs font-semibold uppercase tracking-wide text-steel">Amount</th>
          </tr>
        </thead>
        <tbody>
          {invoice.lines.map((l, i) => (
            <tr key={i} className="border-b border-sand">
              <td className="py-2 text-right tabular-nums text-steel">{i + 1}</td>
              <td className="py-2">
                {l.itemName ?? "—"}
                {l.sku && <span className="ml-2 text-xs text-steel">{l.sku}</span>}
              </td>
              <td className="py-2 text-right tabular-nums">
                {qty(l.quantity)} {l.unitSymbol ?? ""}
              </td>
              <td className="py-2 text-right tabular-nums">{money(l.unitPrice)}</td>
              <td className="py-2 text-right tabular-nums">{money(l.lineTotal)}</td>
            </tr>
          ))}
        </tbody>
        </table>
      </div>

      {/* Discount, tax and shipping only appear when they're not zero — an
          invoice with none of them shouldn't carry three rows of "0.00". */}
      <div className="mt-6 flex justify-end">
        <dl className="grid w-72 grid-cols-[1fr_auto] gap-y-1 text-sm">
          <dt className="text-steel">Subtotal</dt>
          <dd className="text-right tabular-nums">{money(invoice.subtotal)}</dd>
          {discount > 0 && (
            <>
              <dt className="text-steel">Discount</dt>
              <dd className="text-right tabular-nums">-{money(discount)}</dd>
            </>
          )}
          {tax > 0 && (
            <>
              <dt className="text-steel">Tax</dt>
              <dd className="text-right tabular-nums">+{money(tax)}</dd>
            </>
          )}
          {shipping > 0 && (
            <>
              <dt className="text-steel">Shipping</dt>
              <dd className="text-right tabular-nums">+{money(shipping)}</dd>
            </>
          )}
          <dt className="mt-1 border-t border-sand pt-1 font-semibold text-ink">Grand Total</dt>
          <dd className="mt-1 border-t border-sand pt-1 text-right font-semibold tabular-nums text-ink">{money(invoice.grandTotal)}</dd>
          <dt className="text-steel">Paid</dt>
          <dd className="text-right tabular-nums">{money(invoice.paidAmount)}</dd>
          <dt className="font-semibold text-ink">Balance Due</dt>
          <dd className="text-right font-semibold tabular-nums text-ink">{money(balance)}</dd>
        </dl>
      </div>

      <p className="mt-10 border-t border-sand pt-4 text-xs text-steel">
        Generated by {invoice.companyName}. Goods once sold are not returnable without this invoice.
      </p>
    </div>
  );
}
