"use client";

import { useEffect, useRef, useState } from "react";
import { formatDate, money, qty } from "@/lib/format";
import { downloadInvoicePdf, type Invoice } from "@/lib/invoice-pdf";
import { downloadInvoicePng } from "@/lib/invoice-png";

export type { Invoice };

// How the image button finds the document to photograph. An attribute rather
// than a ref because the two are rendered side by side by a server component,
// with no client parent to hold one.
const DOCUMENT_ATTRIBUTE = "data-invoice-document";

// The invoice as a web page — read it, check it, hand the screen to someone.
// The file people actually send out is generated by lib/invoice-pdf.ts, which
// draws this same layout into a real PDF.
//
// The two are separate layouts and have to be edited together. That's the price
// of a one-click download: the browser cannot write a PDF to disk without its
// print dialog, so producing a file with no dialog means drawing it ourselves.
// The print styles here still work if anyone hits Ctrl+P.


// Same generator the invoice list's row button uses, so there is one way to
// produce a PDF rather than a print dialog here and a real file there.
export function DownloadInvoiceButton({ invoice }: { invoice: Invoice }) {
  return (
    <button
      type="button"
      onClick={() => downloadInvoicePdf(invoice)}
      className="h-11 rounded bg-navy-800 px-5 text-sm font-semibold text-white hover:bg-navy-700 print:hidden"
    >
      Download PDF
    </button>
  );
}

// The invoice as a PNG, photographed off the copy already on screen.
//
// The list has no invoice on screen, so it renders one first — see
// InvoiceImageRenderer below, which is how a row gets a document to photograph
// without a second layout existing anywhere.
export async function downloadInvoiceImage(invoice: Invoice) {
  const onScreen = document.querySelector<HTMLElement>(`[${DOCUMENT_ATTRIBUTE}]`);
  if (!onScreen) throw new Error("There is no invoice on screen to photograph.");
  await downloadInvoicePng(onScreen, invoice);
}

// A real invoice, rendered where nobody can see it, so a list row can be turned
// into a picture. Mounted by whoever needs it (InvoiceManager) for exactly as
// long as it takes: `onReady` fires from an effect, which React runs after the
// browser has laid the thing out — the reason this is a component rather than a
// createRoot() call is that getting that ordering by hand is what silently
// produced a zero-height photograph of nothing.
//
// Behind the page rather than off the side of it: a node parked at
// left:-10000px photographs as nothing (see SheetRenderer in LedgerSheet.tsx for
// the full account), while one sitting under the app's own background at
// z-index -1000 has an ordinary box in an ordinary place. display:none and
// visibility:hidden are out for the related reason — no layout to measure.
//
// The width is max-w-3xl in pixels, so the copy breaks its lines exactly as the
// page does.
export function InvoiceImageRenderer({ invoice, onReady }: { invoice: Invoice; onReady: (node: HTMLElement) => void }) {
  const ref = useRef<HTMLDivElement>(null);
  // Strict Mode mounts, unmounts and mounts again in development to smoke out
  // effects that don't clean up after themselves. This one has nothing to clean
  // up — it hands over a node — but it does have a side effect at the far end,
  // and running it twice downloaded the invoice twice for one click. The ref
  // survives that second mount, which is what makes it the thing to latch on.
  const taken = useRef(false);

  useEffect(() => {
    if (taken.current) return;
    const node = ref.current?.firstElementChild as HTMLElement | null;
    if (!node) return;
    taken.current = true;
    onReady(node);
    // Once per mount: the caller unmounts this as soon as it has its picture.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    // force-light: this becomes a PNG in a customer's chat, so it keeps the
    // light palette regardless of the theme the app is in (globals.css).
    <div ref={ref} aria-hidden className="force-light pointer-events-none fixed top-0 left-0 z-[-1000] w-[768px] bg-white">
      <InvoiceDocument invoice={invoice} />
    </div>
  );
}

// Sits next to the PDF button because which one is wanted depends on where it's
// going: a file for the customer's records, a picture for a chat.
export function DownloadInvoiceImageButton({ invoice }: { invoice: Invoice }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function download() {
    setBusy(true);
    setError(null);
    try {
      await downloadInvoiceImage(invoice);
    } catch {
      // Rasterising is the browser's job and it can decline — an image this big
      // can run the tab out of memory. Say so rather than leaving a dead button.
      setError("Couldn't build the image. The PDF button still works.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="flex flex-col items-end gap-1 print:hidden">
      <button
        type="button"
        onClick={() => void download()}
        disabled={busy}
        className="h-11 rounded border border-navy-800 px-5 text-sm font-semibold text-navy-800 hover:bg-ivory disabled:opacity-40"
      >
        {busy ? "Building…" : "Download Image"}
      </button>
      {error && <p className="max-w-56 text-right text-xs text-error">{error}</p>}
    </div>
  );
}

export function InvoiceDocument({ invoice }: { invoice: Invoice }) {
  const balance = Number(invoice.grandTotal) - Number(invoice.paidAmount);
  const discount = Number(invoice.discountTotal);
  const tax = Number(invoice.taxTotal);
  const shipping = Number(invoice.shippingTotal);

  return (
    <div
      {...{ [DOCUMENT_ATTRIBUTE]: "" }}
      className="mx-auto w-full max-w-3xl rounded-lg border border-sand bg-white p-8 text-ink print:max-w-none print:rounded-none print:border-0 print:p-0"
    >
      <div className="flex flex-wrap items-start justify-between gap-6 border-b border-sand pb-6">
        <div>
          <h1 className="text-2xl font-semibold text-navy-800">{invoice.companyName}</h1>
          {invoice.companyAddress && <p className="mt-1 whitespace-pre-line text-sm text-steel">{invoice.companyAddress}</p>}
          <p className="mt-1 text-sm text-steel">
            {[invoice.companyPhone, invoice.companyEmail].filter(Boolean).join(" · ")}
          </p>
          {invoice.companyTaxNumber && <p className="text-sm text-steel">NTN: {invoice.companyTaxNumber}</p>}
        </div>
        <div className="text-right">
          <p className="text-xs font-semibold uppercase tracking-wide text-steel">Invoice</p>
          <p className="text-xl font-semibold text-navy-800">{invoice.number}</p>
          <p className="mt-1 text-sm text-steel">{formatDate(invoice.documentDate)}</p>
          <p className="mt-2 text-sm font-semibold text-ink">
            {invoice.isPaid ? "Paid" : Number(invoice.paidAmount) > 0 ? "Part paid" : "Unpaid"}
          </p>
        </div>
      </div>

      <div className="py-6">
        <p className="text-xs font-semibold uppercase tracking-wide text-steel">Billed to</p>
        <p className="mt-1 text-base font-medium text-ink">{invoice.customerName ?? "—"}</p>
        {invoice.customerAddress && <p className="whitespace-pre-line text-sm text-steel">{invoice.customerAddress}</p>}
        <p className="text-sm text-steel">{[invoice.customerCity, invoice.customerPhone].filter(Boolean).join(" · ")}</p>
      </div>

      <div className="scroll-thin overflow-x-auto print:overflow-visible">
        <table className="w-full min-w-[30rem] border-collapse text-sm print:min-w-0">
        <thead>
          <tr className="border-y border-sand">
            <th className="w-10 py-2 text-right text-xs font-semibold uppercase tracking-wide text-steel">#</th>
            <th className="py-2 text-left text-xs font-semibold uppercase tracking-wide text-steel">Item</th>
            <th className="w-24 py-2 text-right text-xs font-semibold uppercase tracking-wide text-steel">Qty</th>
            <th className="w-28 py-2 text-right text-xs font-semibold uppercase tracking-wide text-steel">Rate</th>
            <th className="w-32 py-2 text-right text-xs font-semibold uppercase tracking-wide text-steel">Amount</th>
          </tr>
        </thead>
        <tbody>
          {invoice.lines.map((l, i) => (
            <tr key={i} className="border-b border-sand">
              <td className="py-2 text-right tabular-nums text-steel">{i + 1}</td>
              <td className="py-2">
                {l.itemName ?? "—"}
                {l.sku && <span className="ml-2 text-xs text-steel">{l.sku}</span>}
              </td>
              <td className="py-2 text-right tabular-nums">
                {qty(l.quantity)} {l.unitSymbol ?? ""}
              </td>
              <td className="py-2 text-right tabular-nums">{money(l.unitPrice)}</td>
              <td className="py-2 text-right tabular-nums">{money(l.lineTotal)}</td>
            </tr>
          ))}
        </tbody>
        </table>
      </div>

      {/* Discount, tax and shipping only appear when they're not zero — an
          invoice with none of them shouldn't carry three rows of "0.00". */}
      <div className="mt-6 flex justify-end">
        <dl className="grid w-72 grid-cols-[1fr_auto] gap-y-1 text-sm">
          <dt className="text-steel">Subtotal</dt>
          <dd className="text-right tabular-nums">{money(invoice.subtotal)}</dd>
          {discount > 0 && (
            <>
              <dt className="text-steel">Discount</dt>
              <dd className="text-right tabular-nums">-{money(discount)}</dd>
            </>
          )}
          {tax > 0 && (
            <>
              <dt className="text-steel">Tax</dt>
              <dd className="text-right tabular-nums">+{money(tax)}</dd>
            </>
          )}
          {shipping > 0 && (
            <>
              <dt className="text-steel">Shipping</dt>
              <dd className="text-right tabular-nums">+{money(shipping)}</dd>
            </>
          )}
          <dt className="mt-1 border-t border-sand pt-1 font-semibold text-ink">Grand Total</dt>
          <dd className="mt-1 border-t border-sand pt-1 text-right font-semibold tabular-nums text-ink">{money(invoice.grandTotal)}</dd>
          <dt className="text-steel">Paid</dt>
          <dd className="text-right tabular-nums">{money(invoice.paidAmount)}</dd>
          <dt className="font-semibold text-ink">Balance Due</dt>
          <dd className="text-right font-semibold tabular-nums text-ink">{money(balance)}</dd>
        </dl>
      </div>

      <p className="mt-10 border-t border-sand pt-4 text-xs text-steel">
        Generated by {invoice.companyName}. Goods once sold are not returnable without this invoice.
      </p>
    </div>
  );
}
